ggg

diff --git a/idlman b/idlman
--- a/idlman
+++ b/idlman
@@ -5,21 +5,17 @@ set -x
 
 declare -A already_existing_outfn_sz
 if [[ "$1" = get && $# = 3 ]]; then
-  if [[ -e "$3.ing" ]]; then
-    already_existing_outfn_sz+=("$3" "$(stat -c %s -- "$3.ing")")
-  fi
-  until stdbuf -o 32M curl -q --no-progress-meter -gfL"${${already_existing_outfn_sz[$3]:#0}:+C${already_existing_outfn_sz[$3]}}" -y 185 -Y 10240 --retry 0 --url "$2" <&- >>"$3.ing"; do
+  until {
+    if [[ -e "$3.ing" ]]; then already_existing_outfn_sz+=("$3" "$(stat -c %s -- "$3.ing")"); fi
+    stdbuf -o 32M curl -q --no-progress-meter -gfL"${${already_existing_outfn_sz[$3]:#0}:+C${already_existing_outfn_sz[$3]}}" -y 185 -Y 10240 --retry 0 --url "$2" <&- >>"$3.ing"
+  }; do
     case "$?" in
-     (52)
-     sleep $((RANDOM%30+60))
-     ;|
-     (*)
-       eval "echo return:$? ${(q@)argv} >&2; exit $?"
-     ;|
+     (52) sleep $((RANDOM%30+60)) ;;
+     (*) exit $? ;;
     esac
   done
   mv -vT -- "$3"{".ing",}
-  exit
+  exit $?
 fi
 
 declare +x idlpaste=
